spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/student/**
        
        - id: tutor-service
          uri: lb://tutor-service
          predicates:
            - Path=/api/tutor/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/